 #  https://github.com/helm/charts/blob/master/stable/weave-scope/values.yaml #configuration

name: weave-scope
version: 0.11.0
appVersion: 1.10.1
global:
  image:
    repository: weaveworks/scope
    tag: 1.10.1
    pullPolicy: "IfNotPresent"
  service:
    port: 80
    type: "ClusterIP"
weave-scope-frontend:
  enabled: true
weave-scope-agent:
  enabled: true
  rbac:
    create: true
  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
